spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/webProject?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${db_username:root}
    password: ${db_password:1234}
  sql:
    init:
      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          jdbc.bind: DEBUG


